### ISSUE TITLE
duplicated column names in one_week_analysis.R

### ISSUE THREAD

**Issue by jhofman** [msr-ds3/nyctaxi#1]
I'm seeing two issues with `one_week_analysis.R`. First, `coordinates` and `proj4string` complain about having a `tbl_df` instead of normal data frame, but that's easily fixed with an `as.data.frame` coercion.

Second, [line 52](https://github.com/msr-ds3/nyctaxi/blob/master/exploratory_analysis/one_week_analysis.R#L52) complains about duplicate column names:

`Error: found duplicated column name: neighborhood, boroughCode, borough, X.id, neighborhood, boroughCode, borough, X.id, neighborhood, boroughCode, borough, X.id, neighborhood, boroughCode, borough, X.id`

Any idea what's up?

**Comment by jaipunjwani** [comment]
That's strange, [line 42](https://github.com/msr-ds3/nyctaxi/blob/master/exploratory_analysis/one_week_analysis.R#L42) should take care of renaming the column (it has been doing so for all of us).

**Comment by jhofman** [comment]
somehow a pull and clear of environment has fixed everything up. looks good now.

just committed the as.data.frame coercion.
